defaults:
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models
  phoneme_dir: config/phonemes.json


phoneme_sort_strategy: da
sampling_probabilities:
  dates: 0.0625
  times: 0.0625
  bus_stops_and_stations: 0.125
  lex: 0.375
  phoneme_covering: 0.375
