defaults:
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models
  phoneme_file: phonemes.json

random_seed: 703

sampling_probabilities:
  dates: 0.05
  lex: 0.35
  sundhed_dk: 0.35
  borger_dk: 0.25

include_entire_dataset:
  - phoneme_covering
  - bus_stops_and_stations
  - reddit
  - times

min_sentence_length: 30
min_docs_per_phoneme: 30
scraping_retry_connection_limit: 20
