defaults:
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models

phoneme_filename: phonemes.json
phoneme_sort_strategy: da
sampling_probabilities:
  dates: 0.125
  times: 0.125
  bus_stops_and_stations: 0.25
  lex: 0.5
