defaults:
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models
  phoneme_file: phonemes.json

split_strings:
  - \t
  - \n
  - _NEWLINE_
  - _START_ARTICLE_
  - _START_SECTION_
  - _START_PARAGRAPH_

sampling_probabilities:
  dates: 0.0625
  times: 0.0625
  bus_stops_and_stations: 0.125
  lex: 0.375

include_entire_dataset:
  - phoneme_covering

phoneme_covering:
  phoneme_sort_strategy: da
  min_docs_per_phoneme: 20
