defaults:
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models
  phoneme_file: phonemes.json

random_seed: 703

sampling_probabilities:
  dates: 0.10
  times: 0.10
  bus_stops_and_stations: 0.20
  lex: 0.30
  sundhed_dk: 0.30

include_entire_dataset:
  - phoneme_covering

min_sentence_length: 30
min_docs_per_phoneme: 30
