defaults:
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models
  phoneme_file: phonemes.json

sampling_probabilities:
  dates: 0.0625
  times: 0.0625
  bus_stops_and_stations: 0.125
  lex: 0.375

include_entire_dataset:
  - phoneme_covering

min_sentence_length: 30
min_docs_per_phoneme: 20
