defaults:
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models

phoneme_filename: phonemes.json
phoneme_sort_strategy: da