defaults:
  - override hydra/job_logging: custom
  - _self_

dirs:
  data: data
  raw: raw
  processed: processed
  final: final
  models: models
  phoneme_file: phonemes.json

split_strings:
  - \t
  - \n
  - _NEWLINE_
  - _START_ARTICLE_
  - _START_SECTION_
  - _START_PARAGRAPH_

phoneme_sort_strategy: da
sampling_probabilities:
  dates: 0.125
  times: 0.125
  bus_stops_and_stations: 0.125
  lex: 0.25
  reddit: 0.125
  phoneme_covering: 0.25
